title: DeepLog
email: kwanwoo.kim@gmail.com
description: ''
github_username: deeplog
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
date_format: '%Y-%M-%D'
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/
collectrions:
  authors:
    title: Authors
    output: true
